# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=github.com/skelterjohn/gmd
GOFILES=\


CGOFILES=\
	events.go\
	gmdgo.go\
	image.go\

include $(GOROOT)/src/Make.pkg
